NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12	
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0

NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 4
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0

NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 20
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30


NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7

NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0